job_template: &template
  working_directory: /tmp/dozer
  docker:
    - image: circleci/openjdk:8-jdk
  environment:
    # set the JVM heap limit
    MAVEN_OPTS: -Xmx3200m

version: 2
jobs:
  prepare:
    <<: *template
    steps:
      - checkout

      # download cached dependencies
      - restore_cache:
          keys:
            - dozer-{{ checksum "pom.xml" }}
            - dozer- # fallback to the latest cache

      - run:
          name: Install dependencies
          command: mvn dependency:go-offline

      # save any cache updates
      - save_cache:
          paths:
            - ~/.m2
          key: dozer-{{ checksum "pom.xml" }}

      # save the dependencies for downstream jobs
      - persist_to_workspace:
          root: /tmp/dozer
          paths:
            - .

  artifact:
    <<: *template
    steps:
      - attach_workspace:
          at: /tmp/dozer

      - run:
          name: Build Dozer.jar
          command: mvn package

      # release Dozer.jar as a CircleCI artifact
      - store_artifacts:
          path: target/Dozer.jar
          destination: Dozer.jar

      # persist Dozer.jar to the test and deploy steps
      - persist_to_workspace:
          root: /tmp/dozer
          paths:
            - target/Dozer.jar

  unit_test:
    <<: *template
    steps:
      - attach_workspace:
          at: /tmp/dozer

#      - run:
#          name: Run unit tests
#          command: mvn unit-tests

  deploy:
    <<: *template
    steps:
      - attach_workspace:
          at: /tmp/dozer

      - run:
          name: Install GitHub Releases management tool
          command: 

      - run:
          name: Upload Dozer.jar to GitHub Releases
          command: 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - prepare
      - artifact:
          requires:
            - prepare
      - unit_test:
          requires:
            - artifact
      - deploy:
          type: approval # requires manual interaction
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/
          requires:
            - unit_test
